/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OutboundRouteImport } from './routes/outbound'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as InboundRouteImport } from './routes/inbound'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OutboundRoute = OutboundRouteImport.update({
  id: '/outbound',
  path: '/outbound',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const InboundRoute = InboundRouteImport.update({
  id: '/inbound',
  path: '/inbound',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/history': typeof HistoryRoute
  '/inbound': typeof InboundRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/outbound': typeof OutboundRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/stores': typeof StoresRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/history': typeof HistoryRoute
  '/inbound': typeof InboundRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/outbound': typeof OutboundRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/stores': typeof StoresRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/history': typeof HistoryRoute
  '/inbound': typeof InboundRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/outbound': typeof OutboundRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/stores': typeof StoresRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/history'
    | '/inbound'
    | '/inventory'
    | '/login'
    | '/outbound'
    | '/register'
    | '/reports'
    | '/stores'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/history'
    | '/inbound'
    | '/inventory'
    | '/login'
    | '/outbound'
    | '/register'
    | '/reports'
    | '/stores'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/history'
    | '/inbound'
    | '/inventory'
    | '/login'
    | '/outbound'
    | '/register'
    | '/reports'
    | '/stores'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  HistoryRoute: typeof HistoryRoute
  InboundRoute: typeof InboundRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  OutboundRoute: typeof OutboundRoute
  RegisterRoute: typeof RegisterRoute
  ReportsRoute: typeof ReportsRoute
  StoresRoute: typeof StoresRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outbound': {
      id: '/outbound'
      path: '/outbound'
      fullPath: '/outbound'
      preLoaderRoute: typeof OutboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbound': {
      id: '/inbound'
      path: '/inbound'
      fullPath: '/inbound'
      preLoaderRoute: typeof InboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  HistoryRoute: HistoryRoute,
  InboundRoute: InboundRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  OutboundRoute: OutboundRoute,
  RegisterRoute: RegisterRoute,
  ReportsRoute: ReportsRoute,
  StoresRoute: StoresRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
